### ISSUE TITLE
Ang2AutocompleteModule is not an NgModule

### ISSUE THREAD

**Issue by sherifhamdyhamdy** [r-vishnu/ang2-autocomplete#1]
I'm use WebPack and  following the steps but it give me this issue:

ERROR in Ang2AutocompleteModule is not an NgModule

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ang2-autocomplete' in 'D:\sherifWS\CurrentSystem\BOMNewDesign\UI\SE2_PartDetail_UI\src\app'
 @ ./src/app/app.module.ts 19:0-59
 @ ./src/app/browser-app.module.ts
 @ ./src/main.browser.ts
Child html-webpack-plugin for "index.html":
       [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 308 bytes {0} [built]

**Comment by r-vishnu** [comment]
Sorry this lib was for angular 2 version,  Now we have updated it to angular 19
